version: 2

project_name: terraform-provider-raysouz

before:
  hooks:
  - go mod tidy

builds:
- id: terraform-provider
  main: .
  binary: terraform-provider-raysouz
  goos: [ linux, darwin, windows ]
  goarch: [ amd64, arm64 ]

archives:
- id: release
  builds: [ terraform-provider ]
  format: zip
  name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "SHA256SUMS" # ← nome exato
  algorithm: sha256

release:
  github:
    owner: raywall
    name: terraform-provider-raysouz

announce:
  skip: true
