version: 2

project_name: terraform-provider-raysouz

before:
  hooks:
  - go mod tidy

builds:
- id: terraform-provider
  main: .
  binary: terraform-provider-raysouz
  goos: [ linux, darwin, windows ]
  goarch: [ amd64, arm64 ]

archives:
- id: release
  builds: [ terraform-provider ]
  format: zip
  name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "SHA256SUMS" # ← aspas duplas forçam nome exato
  disable: false # ← garanta que não está desativado

signs:
- artifacts: checksum
  args:
  - --output
  - "SHA256SUMS.sig" # ← força o nome exato do .sig
  - --detach-sign
  - --batch
  - --yes
  - --pinentry-mode
  - loopback
  - --passphrase
  - "{{ .Env.PASSPHRASE }}"
  - "SHA256SUMS" # ← força o arquivo de entrada

release:
  github:
    owner: raywall
    name: terraform-provider-raysouz

announce:
  skip: true
