version: 2

project_name: terraform-provider-raysouz

before:
  hooks:
  - go mod tidy

builds:
- env:
  - CGO_ENABLED=0

  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
  - -trimpath

  ldflags:
  - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}}'

  goos:
  - linux
  - darwin
  - windows

  goarch:
  - amd64
  - arm64

  binary: '{{ .ProjectName }}_v{{ .Version }}'

archives:
- format: zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  files:
  - none*

checksum:
  extra_files:
  - glob: 'terraform-registry-manifest.json'
    name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'

  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
- artifacts: checksum
  signature: "${artifact}.sig"
  cmd: gpg
  args:
  - "--batch"
  - "--local-user"
  - "{{ .Env.GPG_FINGERPRINT }}"
  - "--output"
  - "${signature}"
  - "--detach-sign"
  - "${artifact}"
  # Condição para executar apenas se o fingerprint estiver definido
  ids:
  - "gpg"
  env:
  - GPG_FINGERPRINT

release:
  extra_files:
  - glob: 'terraform-registry-manifest.json'
    name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'

changelog:
  disable: true
