version: 2

project_name: terraform-provider-raysouz

before:
  hooks:
  - go mod tidy

builds:
- env:
  # goreleaser does not work with CGO, it could also complicate
  # usage by users in CI/CD systems like Terraform Cloud where
  # they are unable to install libraries.
  - CGO_ENABLED=0
  mod: mod
  main: .
  ldflags:
  - -X 'main/version={{.Version}}'
  - -X 'main/commit={{.Commit}}'
  - -X 'main/date={{.CommitDate}}'
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  binary: terraform-provider-raysouz

archives:
- format: zip
  name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Tag }}_SHA256SUMS"
  algorithm: sha256

signs:
- artifacts: checksum
  cmd: gpg
  args:
  - --batch
  - --yes
  - --pinentry-mode
  - loopback
  - --passphrase
  - "{{ .Env.GPG_PASSPHRASE }}"
  - --detach-sign
  - --armor
  - "${artifact}"
  output: "${artifact}.sig"

release:
  github:
    owner: raywall
    name: terraform-provider-raysouz
  extra_files:
  - glob: terraform-registry-manifest.json
    # Isso copia o manifesto da raiz para a release sem src/dst (sintaxe v2.x)

announce:
  skip: true
