version: 2

project_name: terraform-provider-raysouz

before:
  hooks:
  - go mod tidy

builds:
- id: terraform-provider
  main: .
  binary: terraform-provider-raysouz
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64

archives:
- id: release
  builds:
  - terraform-provider
  format: zip
  name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "SHA256SUMS"

signs:
- artifacts: checksum # Assina sรณ os checksums (SHA256SUMS)
  cmd: gpg
  args:
  - "--batch"
  - "--yes"
  - "--pinentry-mode"
  - "loopback"
  - "--passphrase"
  - "{{ .Env.PASSPHRASE }}"
  - "--detach-sign"
  - "${artifact}" # <--- MUDE AQUI: Use ${artifact} (caminho do SHA256SUMS)
  output: "${artifact}.sig" # <--- NOVO: Nomeia o .sig corretamente (ex: SHA256SUMS.sig)

release:
  github:
    owner: raywall
    name: terraform-provider-raysouz

announce:
  skip: true
