version: 2

project_name: terraform-provider-raysouz

before:
  hooks:
  - go mod tidy

builds:
- id: provider
  main: .
  binary: terraform-provider-raysouz
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64

archives:
- format: zip
  builds:
  - provider
  name_template: >-
    {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

signs:
- artifacts: all
  cmd: gpg
  signature: "${artifact}.sig"
  args:
  - --output
  - "${signature}"
  - --detach-sign
  - "${artifact}"
  env:
  - "GPG_TTY=/dev/tty"

release:
  draft: false
  prerelease: auto

changelog:
  use: git
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

announce:
  skip: true
