version: 2

project_name: terraform-provider-raysouz

before:
  hooks:
  - go mod tidy

builds:
- id: terraform-provider
  main: .
  binary: terraform-provider-raysouz
  goos: [ linux, darwin, windows ]
  goarch: [ amd64, arm64 ]

archives:
- id: release
  builds: [ terraform-provider ]
  format: zip
  name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"

# ← FORÇA nome EXATO do checksum
checksum:
  name_template: "SHA256SUMS"
  algorithm: sha256

# ← Assina o checksum com nome EXATO SHA256SUMS.sig
signs:
- artifacts: checksum
  args:
  - --output
  - "SHA256SUMS.sig" # ← nome final EXATO (obrigatório)
  - --detach-sign
  - --batch
  - --yes
  - --pinentry-mode
  - loopback
  - --passphrase
  - "{{ .Env.PASSPHRASE }}"
  - "${checksum}" # ← VARIÁVEL CORRETA do GoReleaser (não use "SHA256SUMS")
  # NÃO use `output:` nem force o input como string!

release:
  github:
    owner: raywall
    name: terraform-provider-raysouz

announce:
  skip: true
