version: 2

project_name: terraform-provider-raysouz

before:
  hooks:
  - go mod tidy

builds:
- id: terraform-provider
  main: .
  binary: terraform-provider-raysouz
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64

archives:
- id: release
  builds:
  - terraform-provider
  format: zip
  name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}" # OK para ZIPs individuais

checksum:
  name_template: SHA256SUMS # ← MUDE: Sem prefixo! Gera SHA256SUMS global

signs:
- artifacts: checksum # Assina só checksums
  cmd: gpg
  args:
  # Ordem correta: output primeiro, depois sign
  - --output
  - ${signature} # Gera SHA256SUMS.sig automaticamente
  - --detach-sign
  - --batch
  - --yes
  - --pinentry-mode
  - loopback
  - --passphrase
  - "{{ .Env.PASSPHRASE }}"
  - ${artifact} # Caminho do SHA256SUMS
  output: "${artifact}.sig" # <--- NOVO: Nomeia o .sig corretamente (ex: SHA256SUMS.sig)

release:
  github:
    owner: raywall
    name: terraform-provider-raysouz

announce:
  skip: true
